import { EditorElement } from '../editorStore';

export type TemplateCategory = 
  | 'Flyere' 
  | 'Cărți de vizită' 
  | 'Postere' 
  | 'Bannere' 
  | 'Social Media' 
  | 'Prezentări'
  | 'Invitații';

export type TemplateStyle = 'modern' | 'minimalist' | 'elegant' | 'corporate' | 'creative';

export interface Template {
  id: string;
  name: string;
  category: TemplateCategory;
  style: TemplateStyle;
  thumbnail: string;
  description: string;
  dominantColors: string[];
  canvasSize: { width: number; height: number };
  elements: EditorElement[];
}

// Template-uri demo pentru testare
export const templates: Template[] = [
  // FLYERE
  {
    id: 'flyer-modern-1',
    name: 'Flyer Modern Business',
    category: 'Flyere',
    style: 'modern',
    thumbnail: '/templates/flyer-modern-1.jpg',
    description: 'Design modern pentru evenimente business',
    dominantColors: ['#0066FF', '#FFFFFF', '#111827'],
    canvasSize: { width: 800, height: 1000 },
    elements: [
      {
        id: 'bg-1',
        type: 'shape',
        x: 0,
        y: 0,
        width: 800,
        height: 400,
        shape: 'rectangle',
        fill: '#0066FF',
        rotation: 0,
        opacity: 1,
        zIndex: 0,
        visible: true,
        locked: false,
      },
      {
        id: 'title-1',
        type: 'text',
        x: 50,
        y: 100,
        width: 700,
        height: 120,
        content: 'EVENIMENT BUSINESS',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: 800,
        color: '#FFFFFF',
        textAlign: 'center',
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        visible: true,
        locked: false,
      },
      {
        id: 'subtitle-1',
        type: 'text',
        x: 100,
        y: 240,
        width: 600,
        height: 60,
        content: 'Alătură-te nouă pentru o experiență unică',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 400,
        color: '#FFFFFF',
        textAlign: 'center',
        rotation: 0,
        opacity: 0.9,
        zIndex: 1,
        visible: true,
        locked: false,
      },
      {
        id: 'accent-1',
        type: 'shape',
        x: 50,
        y: 500,
        width: 200,
        height: 200,
        shape: 'circle',
        fill: '#FACC15',
        rotation: 0,
        opacity: 0.8,
        zIndex: 0,
        visible: true,
        locked: false,
      },
      {
        id: 'info-1',
        type: 'text',
        x: 100,
        y: 750,
        width: 600,
        height: 150,
        content: 'Data: 15 Ianuarie 2026\nLocație: Centrul de Conferințe\nContact: info@eveniment.ro',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 400,
        color: '#111827',
        textAlign: 'left',
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        visible: true,
        locked: false,
      },
    ],
  },
  {
    id: 'flyer-minimalist-1',
    name: 'Flyer Minimalist',
    category: 'Flyere',
    style: 'minimalist',
    thumbnail: '/templates/flyer-minimalist-1.jpg',
    description: 'Design minimalist și elegant',
    dominantColors: ['#111827', '#FFFFFF', '#F3F4F6'],
    canvasSize: { width: 800, height: 1000 },
    elements: [
      {
        id: 'bg-2',
        type: 'shape',
        x: 0,
        y: 0,
        width: 800,
        height: 1000,
        shape: 'rectangle',
        fill: '#FFFFFF',
        rotation: 0,
        opacity: 1,
        zIndex: 0,
        visible: true,
        locked: false,
      },
      {
        id: 'line-1',
        type: 'shape',
        x: 100,
        y: 200,
        width: 600,
        height: 4,
        shape: 'rectangle',
        fill: '#111827',
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        visible: true,
        locked: false,
      },
      {
        id: 'title-2',
        type: 'text',
        x: 100,
        y: 300,
        width: 600,
        height: 100,
        content: 'SIMPLITATE',
        fontSize: 72,
        fontFamily: 'Inter',
        fontWeight: 300,
        color: '#111827',
        textAlign: 'center',
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        visible: true,
        locked: false,
      },
      {
        id: 'subtitle-2',
        type: 'text',
        x: 100,
        y: 420,
        width: 600,
        height: 60,
        content: 'Eleganță în simplitate',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 400,
        color: '#6B7280',
        textAlign: 'center',
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        visible: true,
        locked: false,
      },
    ],
  },

  // CĂRȚI DE VIZITĂ
  {
    id: 'business-card-corporate-1',
    name: 'Card Corporate',
    category: 'Cărți de vizită',
    style: 'corporate',
    thumbnail: '/templates/business-card-1.jpg',
    description: 'Design profesional pentru business',
    dominantColors: ['#111827', '#0066FF', '#FFFFFF'],
    canvasSize: { width: 900, height: 500 },
    elements: [
      {
        id: 'bg-3',
        type: 'shape',
        x: 0,
        y: 0,
        width: 450,
        height: 500,
        shape: 'rectangle',
        fill: '#111827',
        rotation: 0,
        opacity: 1,
        zIndex: 0,
        visible: true,
        locked: false,
      },
      {
        id: 'accent-2',
        type: 'shape',
        x: 450,
        y: 0,
        width: 450,
        height: 500,
        shape: 'rectangle',
        fill: '#FFFFFF',
        rotation: 0,
        opacity: 1,
        zIndex: 0,
        visible: true,
        locked: false,
      },
      {
        id: 'name-1',
        type: 'text',
        x: 50,
        y: 150,
        width: 350,
        height: 80,
        content: 'JOHN DOE',
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: 700,
        color: '#FFFFFF',
        textAlign: 'left',
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        visible: true,
        locked: false,
      },
      {
        id: 'title-3',
        type: 'text',
        x: 50,
        y: 240,
        width: 350,
        height: 40,
        content: 'CEO & Founder',
        fontSize: 18,
        fontFamily: 'Inter',
        fontWeight: 400,
        color: '#0066FF',
        textAlign: 'left',
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        visible: true,
        locked: false,
      },
      {
        id: 'contact-1',
        type: 'text',
        x: 500,
        y: 200,
        width: 350,
        height: 120,
        content: '+40 123 456 789\njohn@company.com\nwww.company.com',
        fontSize: 16,
        fontFamily: 'Inter',
        fontWeight: 400,
        color: '#111827',
        textAlign: 'left',
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        visible: true,
        locked: false,
      },
    ],
  },

  // POSTERE
  {
    id: 'poster-creative-1',
    name: 'Poster Creativ',
    category: 'Postere',
    style: 'creative',
    thumbnail: '/templates/poster-creative-1.jpg',
    description: 'Design creativ pentru evenimente',
    dominantColors: ['#FACC15', '#0066FF', '#111827'],
    canvasSize: { width: 800, height: 1200 },
    elements: [
      {
        id: 'bg-4',
        type: 'shape',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        shape: 'rectangle',
        fill: '#FACC15',
        rotation: 0,
        opacity: 1,
        zIndex: 0,
        visible: true,
        locked: false,
      },
      {
        id: 'circle-1',
        type: 'shape',
        x: 150,
        y: 200,
        width: 500,
        height: 500,
        shape: 'circle',
        fill: '#0066FF',
        rotation: 0,
        opacity: 0.9,
        zIndex: 1,
        visible: true,
        locked: false,
      },
      {
        id: 'title-4',
        type: 'text',
        x: 100,
        y: 800,
        width: 600,
        height: 120,
        content: 'CREATIVITATE',
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: 800,
        color: '#111827',
        textAlign: 'center',
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        visible: true,
        locked: false,
      },
      {
        id: 'subtitle-3',
        type: 'text',
        x: 100,
        y: 940,
        width: 600,
        height: 60,
        content: 'Inspirație pentru design modern',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 400,
        color: '#111827',
        textAlign: 'center',
        rotation: 0,
        opacity: 0.8,
        zIndex: 2,
        visible: true,
        locked: false,
      },
    ],
  },

  // SOCIAL MEDIA
  {
    id: 'social-instagram-1',
    name: 'Instagram Post',
    category: 'Social Media',
    style: 'modern',
    thumbnail: '/templates/instagram-1.jpg',
    description: 'Template pentru Instagram',
    dominantColors: ['#E4405F', '#FFFFFF', '#111827'],
    canvasSize: { width: 1080, height: 1080 },
    elements: [
      {
        id: 'bg-5',
        type: 'shape',
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        shape: 'rectangle',
        fill: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        rotation: 0,
        opacity: 1,
        zIndex: 0,
        visible: true,
        locked: false,
      },
      {
        id: 'content-box',
        type: 'shape',
        x: 90,
        y: 340,
        width: 900,
        height: 400,
        shape: 'rectangle',
        fill: '#FFFFFF',
        borderRadius: 20,
        rotation: 0,
        opacity: 0.95,
        zIndex: 1,
        visible: true,
        locked: false,
      },
      {
        id: 'title-5',
        type: 'text',
        x: 140,
        y: 450,
        width: 800,
        height: 100,
        content: 'FOLLOW US',
        fontSize: 72,
        fontFamily: 'Inter',
        fontWeight: 800,
        color: '#667eea',
        textAlign: 'center',
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        visible: true,
        locked: false,
      },
      {
        id: 'handle',
        type: 'text',
        x: 140,
        y: 580,
        width: 800,
        height: 60,
        content: '@yourbrand',
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: 600,
        color: '#111827',
        textAlign: 'center',
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        visible: true,
        locked: false,
      },
    ],
  },

  // BANNERE
  {
    id: 'banner-web-1',
    name: 'Banner Web',
    category: 'Bannere',
    style: 'modern',
    thumbnail: '/templates/banner-1.jpg',
    description: 'Banner pentru website',
    dominantColors: ['#0066FF', '#FFFFFF', '#FACC15'],
    canvasSize: { width: 1200, height: 400 },
    elements: [
      {
        id: 'bg-6',
        type: 'shape',
        x: 0,
        y: 0,
        width: 1200,
        height: 400,
        shape: 'rectangle',
        fill: '#0066FF',
        rotation: 0,
        opacity: 1,
        zIndex: 0,
        visible: true,
        locked: false,
      },
      {
        id: 'accent-3',
        type: 'shape',
        x: 900,
        y: -100,
        width: 400,
        height: 400,
        shape: 'circle',
        fill: '#FACC15',
        rotation: 0,
        opacity: 0.3,
        zIndex: 1,
        visible: true,
        locked: false,
      },
      {
        id: 'title-6',
        type: 'text',
        x: 100,
        y: 100,
        width: 800,
        height: 100,
        content: 'OFERTĂ SPECIALĂ',
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: 800,
        color: '#FFFFFF',
        textAlign: 'left',
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        visible: true,
        locked: false,
      },
      {
        id: 'subtitle-4',
        type: 'text',
        x: 100,
        y: 220,
        width: 600,
        height: 60,
        content: 'Reducere 50% la toate produsele',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 400,
        color: '#FFFFFF',
        textAlign: 'left',
        rotation: 0,
        opacity: 0.9,
        zIndex: 2,
        visible: true,
        locked: false,
      },
    ],
  },
];

// Funcție helper pentru filtrare
export const filterTemplates = (options: {
  searchQuery?: string;
  category?: TemplateCategory;
  style?: TemplateStyle;
} = {}): Template[] => {
  const { searchQuery = '', category, style } = options;
  
  return templates.filter((template: Template) => {
    const matchesSearch = 
      searchQuery === '' || 
      template.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      template.description.toLowerCase().includes(searchQuery.toLowerCase());
    
    const matchesCategory = !category || template.category === category;
    const matchesStyle = !style || template.style === style;

    return matchesSearch && matchesCategory && matchesStyle;
  });
};

// Categorii disponibile
export const categories: TemplateCategory[] = [
  'Flyere',
  'Cărți de vizită',
  'Postere',
  'Bannere',
  'Social Media',
  'Prezentări',
  'Invitații',
];

// Stiluri disponibile
export const styles: TemplateStyle[] = [
  'modern',
  'minimalist',
  'elegant',
  'corporate',
  'creative',
];
