-- Align machine schema with the current equipment form and API payload
ALTER TYPE "EquipmentType" ADD VALUE IF NOT EXISTS 'DIGITAL_COLOR';
ALTER TYPE "EquipmentType" ADD VALUE IF NOT EXISTS 'DIGITAL_MONO';
ALTER TYPE "EquipmentType" ADD VALUE IF NOT EXISTS 'UV';
ALTER TYPE "EquipmentType" ADD VALUE IF NOT EXISTS 'DTF';
ALTER TYPE "EquipmentType" ADD VALUE IF NOT EXISTS 'SUBLIMATION';
ALTER TYPE "EquipmentType" ADD VALUE IF NOT EXISTS 'OFFSET';
ALTER TYPE "EquipmentType" ADD VALUE IF NOT EXISTS 'EMBROIDERY';
ALTER TYPE "EquipmentType" ADD VALUE IF NOT EXISTS 'PLOTTER_CUTTING';

ALTER TABLE "machines"
  ADD COLUMN IF NOT EXISTS "productionMode" TEXT NOT NULL DEFAULT 'IN_HOUSE',
  ADD COLUMN IF NOT EXISTS "printMarginsMm" DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS "purchaseCostMdl" DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS "expectedLifetimePages" INTEGER,
  ADD COLUMN IF NOT EXISTS "electricityCostPerKwh" DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS "speedProfiles" JSONB,
  ADD COLUMN IF NOT EXISTS "maintenanceComponents" JSONB,
  ADD COLUMN IF NOT EXISTS "tonerConsumables" JSONB;

UPDATE "machines"
SET "productionMode" = 'IN_HOUSE'
WHERE "productionMode" IS NULL;

ALTER TABLE "machines"
  ALTER COLUMN "equipmentType" SET DEFAULT 'DIGITAL_COLOR';

UPDATE "machines"
SET "equipmentType" = 'DIGITAL_COLOR'
WHERE "equipmentType"::text NOT IN ('DIGITAL_COLOR','DIGITAL_MONO','UV','LARGE_FORMAT','DTF','SUBLIMATION','OFFSET','EMBROIDERY','PLOTTER_CUTTING');
